snakefile: "../Snakefile"
local-cores: 1
cores: 100000
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: mamba
keep-going: true
jobscript: sge-jobscript.sh
cluster: "sge-submit.py"
cluster-status: "sge-status.py"
latency-wait: 3600
jobs: 256
