###############################################################################
#
#   Packages in conda virtual environment for nTE
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   MODIFICATION: Miguel_Barquin
#   AFFILIATION: University_of_Konstaz
#   CREATED: 20-03-2020
#   MODIFIED: 14-02-2023
#   CONTACT: miguel.barquin@uni-konstanz.de
#
###############################################################################
---

name: nTE

channels:
  - bioconda
  - conda-forge

dependencies:
  - bash=5.0.018
  - snakemake=7.18.2
  - unzip=6.0
  - python=3.9.4
  - pandas=1.2.4
  - pyyaml=5.4.1
  - jinja2=3.0.1
  - graphviz=2.47.2
  - curl=7.77.0
  - r-base=4.1.0
  - r-optparse=1.6.6
  - bioconductor-seqlogo=1.58.0

...